### ISSUE TITLE
Feature: Community site - Redeem - Improvements

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#55]
There’s a lot of confusion with the TARA Points. Many people confuse with “locked” and “redeemable” rewards.
Check the latest design in Figma.

Suggestions:
- [x] add history of transactions with rewards - tackled in #90. 
- [ ] add empty list design (https://www.figma.com/file/PdAFhWcrpYnUAaFA2UIlH8/TARAXA-Community?node-id=2307%3A27524)
- [ ] show all claims in the table, not just the ones that aren't claimed
- [ ] everything should look like in the design (ex: date color)
- [ ] show the first row only if they have an unclaimed amount that's not included in a claim. These two rows for the same value look weird. The simplest way here is to make the backend return the dynamic row.

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/3051409/166902191-9e0195d1-77c0-4282-8901-919e344ddfce.png">

### For later

- [ ] add pie chart so that users know where the lifetime rewards came from. Distinguish staking/delegation rewards and bounty rewards (e.g. 50% staking yields, 50% bounties etc.) 

![Redeem](https://user-images.githubusercontent.com/3051409/153231285-10589160-5e83-4c42-99c0-15168100c199.png)

**Comment by farebord** [comment]
I need more context regarding the history of transactions and the pie chart.

**Comment by VargaElod23** [comment]
@farebord @rattrap I did a bit of an analysis on the current API state for this and here is a suggestion:

In order to eliminate confusion, I suggest to make the whole process of taking out tokens of any source uniform by implementing the following:

- Eliminate or make any `Redeem` button outside of the Redeem page redirect to it.
- List all the claims in the "Claim table" in the Redeem page, add another column with "Source" that contains the type of the claim.
- We should automatise the claim creation. Example scenario: a user completes a bounty, we confirm it and create an entry for a claim of "Bounty" type for them. That should automatically create a table element in the Redeem page and in case claimed, sum into the pie chart under the 'Claim" type.
- Same for staking.
- Same for delegation.
- Etc.
What do you guys think?
